package Interfaz;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 * Ventana principal de la aplicación JavaFit.
 * Es la primera pantalla que ve el usuario al arrancar el programa.
 * Permite acceder al login de socios, al registro y al login de administradores.
 * Muestra una imagen de fondo cargada desde los recursos del proyecto.
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    /**
     * Constructor de VentanaPrincipal.
     * Inicializa la ventana, carga los socios en memoria, establece la imagen de fondo y aplica estilos visuales a los botones.
     */
    public VentanaPrincipal() {
        Logica.Gestor.cargarSocios(); // Cargamos los socios actuales antes de iniciar.
        Logica.Gestor.cargarAdmins();
        PanelFondo contenedorFondo = new PanelFondo("/imagenes/imagen_inicio.jpg"); // Creamos una nueva instancia de Panel Fondo.

        Logica.HerramientasVisuales.ponerIconoJavaFit(this); // Llamamos a la clase Herramientas Visuales para poner icono.

        contenedorFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout()); // Ponemos AbsoluteLayout para poder colocar los componentes.
    
        //Sustituimos el panel por defecto por el nuestro.
        this.setContentPane(contenedorFondo);
      
        initComponents(); //Inicializamos los componentes (botones, etc.)
        
        // Print para confirmar que funcionó.
        System.out.println("Carga inicial finalizada. Socios en memoria: " + Logica.Gestor.getSocios().size());
    
        // 5. Centramos y damos tamaño
        this.setSize(710, 415);
        this.setLocationRelativeTo(null); 
        
        botonIniciarSesion.setBackground(new java.awt.Color(52, 152, 219)); // Personalizamos los botones.
        botonIniciarSesion.setForeground(java.awt.Color.blue);
        botonIniciarSesion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        botonIniciarSesion.setToolTipText("Pulse para iniciar sesión con su cuenta de Socio");
        botonIniciarSesion.setFocusPainted(false);
        botonIniciarSesion.setBorderPainted(false);
        botonIniciarSesion.setContentAreaFilled(false);
        
        botonRegistrarse.setBackground(Color.GREEN);
        botonRegistrarse.setForeground(java.awt.Color.green);
        botonRegistrarse.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        botonRegistrarse.setToolTipText("Pulse para darse de alta en JavaFit");
        botonRegistrarse.setFocusPainted(false);
        botonRegistrarse.setBorderPainted(false);
        botonRegistrarse.setContentAreaFilled(false);
        
        botonIniciarAdmin.setToolTipText("Reservado para administradores");
        botonIniciarAdmin.setBackground(new Color(30,30,30));
        botonIniciarAdmin.setForeground(Color.WHITE);
        botonIniciarAdmin.setBorder(BorderFactory.createLineBorder(new Color(0,255,120)
));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIniciarSesion = new javax.swing.JButton();
        botonRegistrarse = new javax.swing.JButton();
        botonIniciarAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - Menú de Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciarSesion.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(51, 153, 255));
        botonIniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonIniciarSesion.setLabel("Iniciar Sesión");
        botonIniciarSesion.addActionListener(this::botonIniciarSesionActionPerformed);
        getContentPane().add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 190, 40));

        botonRegistrarse.setBackground(new java.awt.Color(153, 255, 153));
        botonRegistrarse.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(102, 255, 102));
        botonRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegistrarse.setLabel("Registrarse");
        botonRegistrarse.addActionListener(this::botonRegistrarseActionPerformed);
        getContentPane().add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 190, 40));

        botonIniciarAdmin.setText("Iniciar sesión como Administrador");
        botonIniciarAdmin.addActionListener(this::botonIniciarAdminActionPerformed);
        getContentPane().add(botonIniciarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la ventana de login de socios y oculta la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        VentanaLogin ventanaDatos = new VentanaLogin(this); // Creamos instancia de ventana.
        this.setVisible(false); // Ocultamos esta.
        ventanaDatos.setVisible(true);  // Hacemos visible la nueva ventana.
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * Abre la ventana de registro de nuevos socios y oculta la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        VentanaRegistro ventanaDatos = new VentanaRegistro(this);
        this.setVisible(false);
        ventanaDatos.setVisible(true);
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    /**
     * Abre la ventana de login de administradores y oculta la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonIniciarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarAdminActionPerformed
        VentanaLoginAdmin loginAdmin = new VentanaLoginAdmin(this);
        loginAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonIniciarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { // Ponemos Nimbus como se indica.
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarAdmin;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarse;
    // End of variables declaration//GEN-END:variables
}

/**
 * Panel personalizado que muestra una imagen de fondo escalada al tamaño del panel.
 * Se usa como contenedor principal de VentanaPrincipal.
 */
class PanelFondo extends javax.swing.JPanel { 
    private java.awt.Image imagen;

    public PanelFondo(String rutaRecurso) {
        java.net.URL url = getClass().getResource(rutaRecurso);
        if (url != null) {
            this.imagen = new javax.swing.ImageIcon(url).getImage();
            this.setOpaque(false);
        }
    }

    /**
     * Sobreescribe el método de pintado para dibujar la imagen de fondo adaptada al tamaño actual del panel.
     * @param g Contexto gráfico sobre el que se dibuja.
     */
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (imagen != null) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            g.setColor(new Color(0, 0, 0, 15));
            g.fillRect(0, 0, getWidth(), getHeight());
        }
    }
}