/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Administrador;
import Logica.Usuario;
import Logica.Gestor;

/**
 * Ventana de inicio de sesión para administradores de JavaFit.
 * Valida el formato del correo y la longitud de la contraseña antes de comprobar las credenciales. Si son correctas, abre el menú de administrador.
 */
public class VentanaLoginAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLoginAdmin.class.getName());
    
    /** Referencia a la ventana desde la que se abrió el login de admin. */
    private javax.swing.JFrame ventanaPadre;

    /**
     * Constructor de VentanaLoginAdmin.
     * @param padre  Ventana desde la que se abre, normalmente VentanaPrincipal.
     */
    public VentanaLoginAdmin(javax.swing.JFrame padre) {
        this.ventanaPadre = padre;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarCorreoAdmin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonIniciarSesion = new javax.swing.JButton();
        registrarContraseñaAdmin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrarCorreoAdmin.setBackground(new java.awt.Color(255, 255, 204));
        registrarCorreoAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registrarCorreoAdmin.addActionListener(this::registrarCorreoAdminActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Correo electrónico");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña");

        botonVolver.setText("Volver atrás");
        botonVolver.addActionListener(this::botonVolverActionPerformed);

        botonIniciarSesion.setBackground(new java.awt.Color(153, 255, 255));
        botonIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonIniciarSesion.setText("Iniciar Sesión");
        botonIniciarSesion.addActionListener(this::botonIniciarSesionActionPerformed);

        registrarContraseñaAdmin.setBackground(new java.awt.Color(255, 255, 204));
        registrarContraseñaAdmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 257, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarContraseñaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarCorreoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(botonVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarCorreoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarContraseñaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarCorreoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCorreoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarCorreoAdminActionPerformed

    /**
     * Cierra el login de admin y restaura la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose(); // Cierra la ventana de login
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true); // Muestra la VentanaPrincipal
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Valida el formato del correo y la contraseña, luego busca el administrador
     * en memoria. Si las credenciales son correctas abre VentanaMenuAdmin.
     * @param evt Evento de acción del botón.
     */
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        String correo = registrarCorreoAdmin.getText().trim();
        String contraseña = new String(registrarContraseñaAdmin.getPassword());
        
        if(!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato de correo es incorrecto.");
            return;
        }
        
        if(contraseña.length() < 5) {
            javax.swing.JOptionPane.showMessageDialog(this, "La contraseña es demasiado corta.");
            return;
        }
        
        // --- LA MAGIA DEL LOGIN ---
        boolean accesoConcedido = false;
        Logica.Administrador adminActual = null;

        System.out.println("Intentando login con:");
        System.out.println("Correo introducido: " + correo);
        System.out.println("Contraseña introducida: '" + contraseña + "'");
        System.out.println("Admins en memoria: " + Logica.Gestor.getAdmins().size());
        
        // 1. EL BUCLE SOLO BUSCA
        for (Logica.Administrador admin : Logica.Gestor.getAdmins()) {
            if (admin.getCorreo().equals(correo) && admin.getContraseña().equals(contraseña)) {
                accesoConcedido = true;
                adminActual = admin;
                break; // Rompemos el bucle al encontrarlo
            }
        } // <-- ESTA ES LA LLAVE MÁGICA QUE CIERRA EL FOR
            
        // 2. LA DECISIÓN ESTÁ FUERA DEL BUCLE
        if (accesoConcedido && adminActual != null) {
            VentanaMenuAdmin menu = new VentanaMenuAdmin(adminActual); 
            menu.setVisible(true);
            this.dispose(); // Cerramos el login
        } else {
            // Si no se concedió el acceso, mostramos el error
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Correo o contraseña incorrectos.", 
                "Error de Acceso", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField registrarContraseñaAdmin;
    private javax.swing.JFormattedTextField registrarCorreoAdmin;
    // End of variables declaration//GEN-END:variables

}