package Interfaz;
import Logica.Socio;
import java.awt.Color;

/**
 * Ventana del menú principal del socio en JavaFit.
 * Permite al socio acceder a las funciones disponibles: reservar actividades, consultar sus reservas, ver/modificar sus datos y cerrar sesión.
 */
public class VentanaMenuSocio extends javax.swing.JFrame {
    
    /** Socio que ha iniciado sesión y está usando la aplicación. */
    private Socio socioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuSocio.class.getName());
    
    /**
     * Constructor de VentanaMenuSocio.
     * @param socio Socio que ha iniciado sesión correctamente.
     */
    public VentanaMenuSocio(Socio socio) {
        this.socioActual = socio;
        initComponents();
        this.setSize(700, 420);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Logica.HerramientasVisuales.ponerIconoJavaFit(this);
        
        // Fondo degradado
        javax.swing.JPanel panelFondo = new javax.swing.JPanel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
            g2d.setPaint(new java.awt.GradientPaint(
                0, 0, new Color(15, 20, 40),
                0, getHeight(), new Color(25, 40, 70)
            ));
            g2d.fillRect(0, 0, getWidth(), getHeight());
        }
    };
    panelFondo.setLayout(null);
    setContentPane(panelFondo);
        
    
    // Titulo
    javax.swing.JLabel lblTitulo = new javax.swing.JLabel("MENÚ DE SOCIO", javax.swing.SwingConstants.CENTER);
    lblTitulo.setFont(new java.awt.Font("Segoe UI Black", java.awt.Font.BOLD, 28));
    lblTitulo.setForeground(new Color(0, 230, 180));
    lblTitulo.setBounds(0, 10, 700, 45);
    panelFondo.add(lblTitulo);
    
    // Botones
    estilizarBoton(botonReservarActividad, "Reservar Actividad", new Color(0, 200, 160));
    botonReservarActividad.setBounds(150, 75, 400, 60);
    panelFondo.add(botonReservarActividad);
    
    estilizarBoton(botonMisReservas, "Mis Reservas", new Color(70, 130, 220));
    botonMisReservas.setBounds(150, 160, 400, 60);
    panelFondo.add(botonMisReservas);

    estilizarBoton(botonDatos, "Mis Datos", new Color(100, 80, 200));
    botonDatos.setBounds(150, 245, 400, 60);
    panelFondo.add(botonDatos);
    
    // ── CERRAR SESIÓN ────────────────────────────────────────────
    botonCerrarSesion.setText("Cerrar Sesión");
    botonCerrarSesion.setBounds(260, 335, 180, 38);
    botonCerrarSesion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    botonCerrarSesion.setForeground(Color.WHITE);
    botonCerrarSesion.setBackground(new Color(180, 40, 40));
    botonCerrarSesion.setFocusPainted(false);
    botonCerrarSesion.setBorderPainted(false);
    botonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent e) {
            botonCerrarSesion.setBackground(new Color(220, 60, 60));
        }
        public void mouseExited(java.awt.event.MouseEvent e) {
            botonCerrarSesion.setBackground(new Color(180, 40, 40));
        }
    });
    panelFondo.add(botonCerrarSesion);
}
    // Estilo de los botones
    private void estilizarBoton(javax.swing.JButton btn, String texto, java.awt.Color color) {
    btn.setText(texto);
    btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    btn.setForeground(java.awt.Color.WHITE);
    btn.setBackground(color);
    btn.setFocusPainted(false);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        botonReservarActividad = new javax.swing.JButton();
        botonMisReservas = new javax.swing.JButton();
        botonDatos = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Socio - JavaFit");
        setBackground(new java.awt.Color(204, 255, 255));

        botonReservarActividad.setBackground(new java.awt.Color(153, 153, 255));
        botonReservarActividad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonReservarActividad.setForeground(new java.awt.Color(255, 255, 255));
        botonReservarActividad.setText("Reservar Actividad");
        botonReservarActividad.addActionListener(this::botonReservarActividadActionPerformed);

        botonMisReservas.setBackground(new java.awt.Color(0, 255, 204));
        botonMisReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonMisReservas.setForeground(new java.awt.Color(255, 255, 255));
        botonMisReservas.setText("Mis Reservas");
        botonMisReservas.addActionListener(this::botonMisReservasActionPerformed);

        botonDatos.setBackground(new java.awt.Color(255, 153, 0));
        botonDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonDatos.setForeground(new java.awt.Color(255, 255, 255));
        botonDatos.setText("Mis datos");
        botonDatos.addActionListener(this::botonDatosActionPerformed);

        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.addActionListener(this::botonCerrarSesionActionPerformed);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 230, 180));
        lblTitulo.setText("MENU DE SOCIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMisReservas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonReservarActividad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCerrarSesion)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonReservarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonMisReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(botonDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la ventana de búsqueda de actividades para que el socio pueda reservar.
     * @param evt Evento de acción del botón.
     */
    private void botonReservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActividadActionPerformed
        if (this.socioActual != null) {
            VentanaBuscarActividad vba = new VentanaBuscarActividad(this, this.socioActual);
            vba.setVisible(true);
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay un socio logueado.");
        }
    }//GEN-LAST:event_botonReservarActividadActionPerformed

    /**
     * Abre la ventana con las reservas activas del socio.
     * @param evt Evento de acción del botón.
     */
    private void botonMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMisReservasActionPerformed
        if (this.socioActual != null) {
            VentanaMisReservas vmr = new VentanaMisReservas(this, this.socioActual);
            vmr.setVisible(true);
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay un socio logueado.");
        }
    }//GEN-LAST:event_botonMisReservasActionPerformed

    /**
     * Abre la ventana con los datos personales del socio.
     * @param evt Evento de acción del botón.
     */
    private void botonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosActionPerformed
// 1. Verificamos que el socio no sea null
        if (this.socioActual != null) {
            VentanaDatosUsuario vdu = new VentanaDatosUsuario(this, this.socioActual);
            vdu.setVisible(true);
            this.setVisible(false);
            
        } else {
            // Si sale este error, el problema viene del Login
            System.out.println("ERROR: socioActual es null en el Menú");
            javax.swing.JOptionPane.showMessageDialog(this, "Error crítico: No se encontraron los datos del usuario.");
        }
    }//GEN-LAST:event_botonDatosActionPerformed

    /**
     * Cierra la sesión del socio y vuelve a la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        this.dispose(); // Cerramos el menú actual
        //Creamos y mostramos la ventana principal de inicio
        VentanaPrincipal inicio = new VentanaPrincipal();
        inicio.setVisible(true);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonDatos;
    private javax.swing.JButton botonMisReservas;
    private javax.swing.JButton botonReservarActividad;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
