package Interfaz;

/**
 * Ventana que permite al administrador crear nuevas actividades deportivas en JavaFit o modificar una actividad existente.
 * Si se abre sin actividad, funciona como formulario de creación.
 * Si se abre con una actividad, rellena los campos automáticamente para editarla.
 * Permite crear tanto actividades normales como actividades especiales con precio y descripción.
 */
public class VentanaCrearActividad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCrearActividad.class.getName());
    
    /** Referencia a la ventana anterior para restaurarla al cerrar. */
    private javax.swing.JFrame ventanaAnterior;
    
    /** Administrador que está creando o modificando la actividad. */
    private Logica.Administrador adminActual;
    
    /** Actividad que se está editando. Null si se está creando una nueva. */
    private Logica.Actividad_Deportiva actividadEnEdicion = null;
    
    /**
     * Constructor para crear una nueva actividad.
     * Inicializa el formulario vacío con los campos de precio y descripción desactivados.
     * @param ventana Ventana anterior desde la que se abre.
     * @param admin Administrador que realiza la acción.
     */
    public VentanaCrearActividad(javax.swing.JFrame ventana, Logica.Administrador admin) {
        this.ventanaAnterior = ventana;
        this.adminActual = admin;
        this.actividadEnEdicion = null;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Crear Actividad");
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (ventanaAnterior != null) {
                ventanaAnterior.setVisible(true);
                ((VentanaConsultarActividad) ventanaAnterior).cargarActividades();
            }
        }
    });
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        
    }
    
    /**
     * Constructor para modificar una actividad existente.
     * Rellena automáticamente los campos con los datos de la actividad recibida.
     * @param ventana Ventana anterior desde la que se abre.
     * @param admin Administrador que realiza la acción.
     * @param actividad Actividad cuyos datos se van a editar.
     */
    public VentanaCrearActividad (javax.swing.JFrame ventana, Logica.Administrador admin, Logica.Actividad_Deportiva actividad) {
        this.ventanaAnterior = ventana;
        this.adminActual = admin;
        this.actividadEnEdicion = actividad;    // Guardamos la actividad que queremos modificar
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("JAVAFIT - Modificar Actividad: " + actividad.getTitulo());
        
        // Llamamos a un método para rellenar los campos automáticamente
        rellenarCamposParaEdicion();
    } 
    
    /**
     * Rellena los campos del formulario con los datos de la actividad en edición.
     * Bloquea el campo título para que no pueda modificarse.
     */
    private void rellenarCamposParaEdicion() {
        // Ponemos los datos de la actividad en los campos de tu ventana
        txtTitulo.setText(actividadEnEdicion.getTitulo());
        txtMonitor.setSelectedItem(actividadEnEdicion.getMonitor_asignado());
        
        txtHoraInicio.setText(actividadEnEdicion.getHorario().getHora_inicio());
        jFormattedTextField1.setText(actividadEnEdicion.getHorario().getHora_final());
        
        comboTipo.setSelectedItem(actividadEnEdicion.getTipo_Actividad());
        ComboSala.setSelectedItem(actividadEnEdicion.getSala().getNombre());
        txtMonitor.setSelectedItem(actividadEnEdicion.getMonitor_asignado());
        txtTitulo.setEditable(false);
        
        botonGuardarCambios.setText("Guardar Cambios");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboSala = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboDia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtMonitor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        botonGuardarCambios = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.addActionListener(this::txtTituloActionPerformed);
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 30));

        jLabel1.setText("Título");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 38, 71, -1));

        txtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 169, 30));

        jLabel2.setText("Hora inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 38, 77, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 193, 34));

        jLabel3.setText("Hora fin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 102, 75, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOGA", "CARDIO", "MUSCULACION", "NATACION" }));
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 172, 34));

        jLabel4.setText("Tipo de Actividad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 102, 102, -1));

        ComboSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala Zen", "Sala Fitness", "Piscina climatizada", "Sala de elípticas", "Sala adaptada MR", "Sala Fitness reducida" }));
        getContentPane().add(ComboSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 172, 36));

        jLabel5.setText("Sala");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 67, -1));

        ComboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        getContentPane().add(ComboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 169, 36));

        jLabel6.setText("Día");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 37, -1));

        txtMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iago Palazón", "Lorena Menéndez", "Paco Díaz", "Natalia Romareda" }));
        getContentPane().add(txtMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 172, 38));

        jLabel7.setText("Monitor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 53, -1));

        botonGuardarCambios.setText("Guardar Cambios");
        botonGuardarCambios.addActionListener(this::botonGuardarCambiosActionPerformed);
        getContentPane().add(botonGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, 66));

        jLabel8.setText("Descripción");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 79, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 126, 36));

        jLabel9.setText("Precio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 37, -1));

        jCheckBox2.setText("¿Actividad Especial?");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jButton2.setText("Volver atrás");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    /**
     * Valida los campos del formulario y crea o guarda la actividad.
     * Si el checkbox de actividad especial está marcado, valida también precio y descripción.
     * Guarda la actividad en el sistema mediante el Gestor.
     * @param evt Evento de acción del botón.
     */
    private void botonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCambiosActionPerformed
            // Validar campos obligatorios
        if (txtTitulo.getText().trim().isEmpty()
            || txtHoraInicio.getText().trim().isEmpty()
            || jFormattedTextField1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Rellena todos los campos obligatorios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
        }

    // Construir Sala
        Logica.Sala sala = ComboSala.getSelectedItem().toString().equals("Sala Zen")
            ? new Logica.Sala("Sala Zen", 20)
            : new Logica.Sala("Sala Fitness", 30);

    // Construir Horario
        Logica.Horario horario = new Logica.Horario(
            ComboDia.getSelectedItem().toString(),
            txtHoraInicio.getText().trim(),
            jFormattedTextField1.getText().trim()
        );

    // Tipo y monitor
        Logica.Tipo_Actividad tipo = Logica.Tipo_Actividad.valueOf(comboTipo.getSelectedItem().toString());
        String monitor = txtMonitor.getSelectedItem().toString();

    // Crear actividad normal o especial
        Logica.Actividad_Deportiva nueva;
        if (jCheckBox2.isSelected()) {
            if (txtPrecio.getText().trim().isEmpty() || txtDescripcion.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Rellena el precio y la descripción.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                double precio = Double.parseDouble(txtPrecio.getText().trim().replace(",", "."));
                nueva = new Logica.Actividad_Especial(precio, txtDescripcion.getText().trim(),
                    txtTitulo.getText().trim(), tipo, sala, horario, monitor, 0, "/imagenes/default.jpg");
            } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
            }
        } else {
            nueva = new Logica.Actividad_Deportiva(txtTitulo.getText().trim(), tipo, sala, horario, monitor, 0, "/imagenes/default.jpg");
    }

    Logica.Gestor.agregar(nueva);
    Logica.Gestor.guardarActividades();
    javax.swing.JOptionPane.showMessageDialog(this, "¡Actividad creada correctamente!");
    this.dispose();
    }//GEN-LAST:event_botonGuardarCambiosActionPerformed

    
    /**
     * Activa o desactiva los campos de precio y descripción
     * según si el checkbox de actividad especial está marcado.
     * @param evt Evento de acción del checkbox.
     */
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        txtDescripcion.setEnabled(jCheckBox2.isSelected());
        txtPrecio.setEnabled(jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * Cierra la ventana y restaura la ventana anterior.
     * @param evt Evento de acción del botón.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if (ventanaAnterior != null) {
            ventanaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboDia;
    private javax.swing.JComboBox<String> ComboSala;
    private javax.swing.JButton botonGuardarCambios;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JComboBox<String> txtMonitor;
    private javax.swing.JFormattedTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
