/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Logica.Socio;
/**
 *
 * @author gdsergio1307
 */
public class VentanaMenuSocio extends javax.swing.JFrame {
    private Socio socioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuSocio.class.getName());
    
    /**
     * Creates new form VentanaMenuSocio
     */
    public VentanaMenuSocio(Socio socio) {
        this.socioActual = socio;
        initComponents();
        this.setSize(710, 415);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        botonReservarActividad = new javax.swing.JButton();
        botonCancelarReserva = new javax.swing.JButton();
        botonMisReservas = new javax.swing.JButton();
        botonDatos = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonReservarActividad.setText("Reservar Actividad");
        botonReservarActividad.addActionListener(this::botonReservarActividadActionPerformed);

        botonCancelarReserva.setText("Cancelar Reserva");
        botonCancelarReserva.addActionListener(this::botonCancelarReservaActionPerformed);

        botonMisReservas.setText("Mis Reservas");
        botonMisReservas.addActionListener(this::botonMisReservasActionPerformed);

        botonDatos.setText("Mis datos");
        botonDatos.addActionListener(this::botonDatosActionPerformed);

        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.addActionListener(this::botonCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonReservarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(botonMisReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCancelarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(botonDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonReservarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMisReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(botonCerrarSesion)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReservarActividadActionPerformed

    private void botonCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCancelarReservaActionPerformed

    private void botonMisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMisReservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMisReservasActionPerformed

    private void botonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosActionPerformed
// 1. Verificamos que el socio no sea null
        if (this.socioActual != null) {
            VentanaDatosUsuario vdu = new VentanaDatosUsuario(this, this.socioActual);
            vdu.setVisible(true);
            this.setVisible(false);
            
        } else {
            // Si sale este error, el problema viene del Login
            System.out.println("ERROR: socioActual es null en el Menú");
            javax.swing.JOptionPane.showMessageDialog(this, "Error crítico: No se encontraron los datos del usuario.");
        }
    }//GEN-LAST:event_botonDatosActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarReserva;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonDatos;
    private javax.swing.JButton botonMisReservas;
    private javax.swing.JButton botonReservarActividad;
    private javax.swing.Box.Filler filler1;
    // End of variables declaration//GEN-END:variables
}
