/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author gdsergio1307
 */
public class VentanaCrearActividad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCrearActividad.class.getName());
    private javax.swing.JFrame ventanaAnterior;
    private Logica.Administrador adminActual;
    /**
     * Creates new form VentanaCrearActividad
     */
    public VentanaCrearActividad(javax.swing.JFrame ventana, Logica.Administrador admin) {
        this.ventanaAnterior = ventana;
        this.adminActual = admin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Crear Actividad");
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (ventanaAnterior != null) {
                ventanaAnterior.setVisible(true);
                ((VentanaConsultarActividad) ventanaAnterior).cargarActividades();
            }
        }
    });
        txtDescripcion.setEnabled(false);
        txtPrecio.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ComboSala = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboDia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComboMonitor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        botonCrearActividad = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.addActionListener(this::txtTituloActionPerformed);
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 30));

        jLabel1.setText("Título");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 38, 71, -1));
        getContentPane().add(txtHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 169, 30));

        jLabel2.setText("Hora inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 38, 77, -1));
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 193, 34));

        jLabel3.setText("Hora fin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 102, 75, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YOGA", "CARDIO", "MUSCULACION", "NATACION" }));
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 172, 34));

        jLabel4.setText("Tipo de Actividad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 102, 102, -1));

        ComboSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala Zen", "Sala Fitness" }));
        getContentPane().add(ComboSala, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 172, 36));

        jLabel5.setText("Sala");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 67, -1));

        ComboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        getContentPane().add(ComboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 169, 36));

        jLabel6.setText("Día");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 37, -1));

        ComboMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monitor 1", "Monitor 2", "Monitor 3", "Monitor 4" }));
        getContentPane().add(ComboMonitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 172, 38));

        jLabel7.setText("Monitor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 53, -1));

        botonCrearActividad.setText("Crear Actividad");
        botonCrearActividad.addActionListener(this::botonCrearActividadActionPerformed);
        getContentPane().add(botonCrearActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, 66));

        jLabel8.setText("Descripción");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 79, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 126, 36));

        jLabel9.setText("Precio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 37, -1));

        jCheckBox2.setText("¿Actividad Especial?");
        jCheckBox2.addActionListener(this::jCheckBox2ActionPerformed);
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jButton2.setText("Volver atrás");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void botonCrearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActividadActionPerformed
            // Validar campos obligatorios
        if (txtTitulo.getText().trim().isEmpty()
            || txtHoraInicio.getText().trim().isEmpty()
            || jFormattedTextField1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Rellena todos los campos obligatorios.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
        }

    // Construir Sala
        Logica.Sala sala = ComboSala.getSelectedItem().toString().equals("Sala Zen")
            ? new Logica.Sala("Sala Zen", 20)
            : new Logica.Sala("Sala Fitness", 30);

    // Construir Horario
        Logica.Horario horario = new Logica.Horario(
            ComboDia.getSelectedItem().toString(),
            txtHoraInicio.getText().trim(),
            jFormattedTextField1.getText().trim()
        );

    // Tipo y monitor
        Logica.Tipo_Actividad tipo = Logica.Tipo_Actividad.valueOf(comboTipo.getSelectedItem().toString());
        String monitor = ComboMonitor.getSelectedItem().toString();

    // Crear actividad normal o especial
        Logica.Actividad_Deportiva nueva;
        if (jCheckBox2.isSelected()) {
            if (txtPrecio.getText().trim().isEmpty() || txtDescripcion.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Rellena el precio y la descripción.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                double precio = Double.parseDouble(txtPrecio.getText().trim().replace(",", "."));
                nueva = new Logica.Actividad_Especial(precio, txtDescripcion.getText().trim(),
                    txtTitulo.getText().trim(), tipo, sala, horario, monitor, 0, "/imagenes/default.jpg");
            } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
            }
        } else {
            nueva = new Logica.Actividad_Deportiva(txtTitulo.getText().trim(), tipo, sala, horario, monitor, 0, "/imagenes/default.jpg");
    }

    Logica.Gestor.agregar(nueva);
    javax.swing.JOptionPane.showMessageDialog(this, "¡Actividad creada correctamente!");
    this.dispose();
    }//GEN-LAST:event_botonCrearActividadActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        txtDescripcion.setEnabled(jCheckBox2.isSelected());
        txtPrecio.setEnabled(jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if (ventanaAnterior != null) {
            ventanaAnterior.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboDia;
    private javax.swing.JComboBox<String> ComboMonitor;
    private javax.swing.JComboBox<String> ComboSala;
    private javax.swing.JButton botonCrearActividad;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JFormattedTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
