/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Interfaz;

import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Sala;
import Logica.Socio;
import Logica.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class VentanaResultadosActividades extends javax.swing.JFrame {
    
    private Socio socioLogueado;
    private ArrayList<Actividad_Deportiva> listaActividadesActual;
    private javax.swing.JFrame ventanaAnterior;
    /**
     * Creates new form VentanaResultadosActividades
     */
    private javax.swing.JFrame ventanaMenu;
    public VentanaResultadosActividades(javax.swing.JFrame menu, Socio socio) {
        initComponents();
        this.ventanaMenu = menu;
        this.socioLogueado = socio; // Guardamos el socio que nos pasan
        this.setLocationRelativeTo(null); // Centra la ventana
        this.setResizable(false);        // Bloquea el tamaño
        this.setTitle("JAVAFIT - Resultados de Búsqueda");
        
        // AÑADIMOS EL EVENTO DE CLIC A LA TABLA
        TablaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = TablaResultados.getSelectedRow();
            if (fila != -1 && listaActividadesActual != null) {
                // Obtenemos la actividad de la lista usando el índice de la fila
                Actividad_Deportiva seleccionada = listaActividadesActual.get(fila);
                actualizarPanelDetalles(seleccionada);
            }
        }
    });
    }
    
    private void actualizarPanelDetalles(Actividad_Deportiva act) {
    // 1. Descripción
        if (act instanceof Actividad_Especial) {
            Actividad_Especial especial = (Actividad_Especial) act;
            txtDescripcion.setText(especial.getDescripcion());
        } else {
            String texto = "Actividad: " + act.getTitulo() + "\n"
                + "Monitor: " + act.getMonitor_asignado() + "\n"
                + "Sala: " + act.getSala().getNombre() + "\n"
                + "Aforo: " + act.getSala().getAforo_maximo() + " personas.";
                txtDescripcion.setText(texto);
        }

    // 2. Imagen
    ImageIcon icono = act.getImagen();
    if (icono != null && icono.getImage() != null) {
        // Usamos tamaño fijo en lugar de getWidth()/getHeight()
        int ancho = 280;
        int alto = 130;

        java.awt.Image imgEscalada = icono.getImage()
                .getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);

        lblFoto2.setIcon(new ImageIcon(imgEscalada));
        lblFoto2.setText("");
    } else {
        lblFoto2.setIcon(null);
        lblFoto2.setText("Sin imagen");
    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        botonVolver = new javax.swing.JButton();
        botonReservarActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JEditorPane();
        lblFoto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        botonVolver.setText("Volver atrás");
        botonVolver.addActionListener(this::botonVolverActionPerformed);

        botonReservarActividad.setText("Reservar Actividad");
        botonReservarActividad.addActionListener(this::botonReservarActividadActionPerformed);

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Actividad", "Tipo", "Sala (Aforo)", "Día", "Horario ", "Monitor", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(botonReservarActividad)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lblFoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(botonReservarActividad)
                .addGap(10, 10, 10)
                .addComponent(botonVolver)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        if (ventanaMenu != null) {
            ventanaMenu.setVisible(true);
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonReservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActividadActionPerformed
        int fila = TablaResultados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una actividad de la tabla.");
            return;
        }

        Actividad_Deportiva seleccionada = listaActividadesActual.get(fila);
        
        // Llamada al método de reserva que añadimos al Gestor
        String resultado = Gestor.realizarReserva(socioLogueado, seleccionada);

        switch (resultado) {
            case "EXITO":
                JOptionPane.showMessageDialog(this, "¡Reserva confirmada!");
                break;
            case "DUPLICADO":
                JOptionPane.showMessageDialog(this, "Ya tienes una reserva para esta actividad.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "LLENO":
                JOptionPane.showMessageDialog(this, "Lo sentimos, no quedan plazas libres.", "Aforo completo", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }//GEN-LAST:event_botonReservarActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void cargarDatosEnTabla(ArrayList<Actividad_Deportiva> lista) {
        this.listaActividadesActual = lista;
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
        modelo.setRowCount(0); 
        
        for (Actividad_Deportiva act : lista) {
            String salaInfo = act.getSala().getNombre() + " (" + act.getSala().getAforo_maximo() + ")";
            String horarioInfo = act.getHorario().getHora_inicio() + " - " + act.getHorario().getHora_final();
            String precioStr = (act instanceof Actividad_Especial) ? ((Actividad_Especial) act).getPrecio() + "€" : "Incluido";

            Object[] fila = {
                act.getTitulo(),
                act.getTipo_Actividad().toString(),
                salaInfo,
                act.getHorario().getDia(),
                horarioInfo,
                act.getMonitor_asignado(),
                precioStr
            };
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaResultados;
    private javax.swing.JButton botonReservarActividad;
    private javax.swing.JButton botonVolver;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JEditorPane txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
