package Interfaz;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 * Ventana de inicio de sesión para socios de JavaFit.
 * Permite al socio introducir su correo y contraseña para acceder al menú principal.
 * Si las credenciales son correctas, abre la VentanaMenuSocio.
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());
    /** Referencia a la ventana principal, para restaurarla si el login se cancela. */
    private javax.swing.JFrame ventanaPrincipal;
    
    /**
     * Constructor de VentanaLogin.
     * Inicializa la ventana y configura el comportamiento al cerrarla.
     * @param principal Ventana principal desde la que se abre el login.
     */
    public VentanaLogin(javax.swing.JFrame principal) {
        this.ventanaPrincipal = principal;
        PanelFondo contenedorFondo = new PanelFondo("/imagenes/fondoIniciarSesion.jpg"); // Creamos una nueva instancia de Panel Fondo.
        Logica.HerramientasVisuales.ponerIconoJavaFit(this); // Llamamos a la clase Herramientas Visuales para poner icono.
        contenedorFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout()); // Ponemos AbsoluteLayout para poder colocar los componentes.
    
        
        this.setContentPane(contenedorFondo);
        initComponents();
        
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        
        this.setSize(710,415);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/LogoJavaFit.png"));
        Image img = icon.getImage().getScaledInstance(
        jLabel5.getWidth(),
        jLabel5.getHeight(),
        Image.SCALE_SMOOTH
        );
        jLabel5.setIcon(new ImageIcon(img));

        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaPrincipal != null) {
                    ventanaPrincipal.setVisible(true);
                }
            }
        });
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iniciaContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        botonConfirmarInicio = new javax.swing.JButton();
        botonVolverLogin = new javax.swing.JButton();
        iniciaCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoJavaFit.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - Ventana de Inicio de Sesión");
        setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CORREO ELECTRÓNICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 130, 20));

        iniciaContraseña.setBackground(new java.awt.Color(204, 255, 255));
        iniciaContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iniciaContraseña.setForeground(new java.awt.Color(51, 51, 51));
        iniciaContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iniciaContraseña.setFocusTraversalPolicyProvider(true);
        iniciaContraseña.addActionListener(this::iniciaContraseñaActionPerformed);
        getContentPane().add(iniciaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Acepto las políticas de privacidad");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        botonConfirmarInicio.setBackground(new java.awt.Color(0, 255, 102));
        botonConfirmarInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonConfirmarInicio.setLabel("Iniciar Sesión");
        botonConfirmarInicio.addActionListener(this::botonConfirmarInicioActionPerformed);
        getContentPane().add(botonConfirmarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, 30));

        botonVolverLogin.setBackground(new java.awt.Color(255, 102, 102));
        botonVolverLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVolverLogin.setLabel("Volver atrás");
        botonVolverLogin.addActionListener(this::botonVolverLoginActionPerformed);
        getContentPane().add(botonVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        iniciaCorreo.setBackground(new java.awt.Color(204, 255, 255));
        iniciaCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iniciaCorreo.setForeground(new java.awt.Color(51, 51, 51));
        iniciaCorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iniciaCorreo.addActionListener(this::iniciaCorreoActionPerformed);
        getContentPane().add(iniciaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void iniciaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciaContraseñaActionPerformed

    /**
     * Cierra la ventana de login y restaura la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void botonVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverLoginActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverLoginActionPerformed

    /**
     * Valida las credenciales introducidas por el socio.
     * Si son correctas, abre el menú del socio y cierra el login y la ventana principal.
     * Si son incorrectas, muestra un mensaje de error.
     * @param evt Evento de acción del botón.
     */
    private void botonConfirmarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarInicioActionPerformed

        // Usamos trim() para quitar espacios accidentales
        String emailIntroducido = iniciaCorreo.getText().trim();
        String pass = new String(iniciaContraseña.getPassword()).trim();

        System.out.println("DEBUG: Intentando entrar con [" + emailIntroducido + "]");

        boolean accesoConcedido = false;
        Logica.Socio socioActual = null;

        
        for (Logica.Socio s : Logica.Gestor.getSocios()) {
            if (s.getCorreo().trim().equalsIgnoreCase(emailIntroducido) &&
                s.getContraseña().trim().equals(pass)) {

                accesoConcedido = true;
                socioActual = s;
                break;
            }
        }

        if (accesoConcedido && socioActual != null) {
    for (java.awt.event.WindowListener wl : this.getWindowListeners()) {
        this.removeWindowListener(wl);
    }

    VentanaMenuSocio menuSocio = new VentanaMenuSocio(socioActual);
    menuSocio.setVisible(true);
    
    if (ventanaPrincipal != null) {
        ventanaPrincipal.dispose();
    }
    
    // Cerramos el Login
    this.dispose(); 
    } else {
    // Si falla mostramos el error
    javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
}

    }//GEN-LAST:event_botonConfirmarInicioActionPerformed

    private void iniciaCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciaCorreoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmarInicio;
    private javax.swing.JButton botonVolverLogin;
    private javax.swing.JPasswordField iniciaContraseña;
    private javax.swing.JTextField iniciaCorreo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
