package Interfaz;
import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Gestor;
import Logica.Socio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 * Ventana que permite al administrador consultar los datos de todos los socios registrados en JavaFit.
 * Muestra una tabla con los socios y un panel lateral con el detalle del socio seleccionado.
 */
public class VentanaConsultarSocios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConsultarSocios.class.getName());
    /** Referencia al menú del administrador para restaurarlo al cerrar. */
    private javax.swing.JFrame ventanaAdmin;
    
    /** Lista de socios mostrados en la tabla, sincronizada con las filas. */
    private ArrayList<Socio> listaSociosActual;
    
    /** Administrador que está consultando los socios. */
    private Logica.Administrador adminActual;

    /**
     * Constructor de VentanaConsultarSocios.
     * Carga los socios en la tabla y añade el listener de clic para mostrar detalles.
     * @param ventanaAdmin Ventana del menú del administrador desde la que se abre.
     * @param admin Administrador que está realizando la consulta.
     */
    public VentanaConsultarSocios(javax.swing.JFrame ventanaAdmin, Logica.Administrador admin) {
        this.adminActual = admin;
        this.ventanaAdmin = ventanaAdmin;
        initComponents();
        jScrollPane1.getViewport().setBackground(new java.awt.Color(15, 20, 40));
        jScrollPane2.getViewport().setBackground(new java.awt.Color(15, 20, 40));
        getContentPane().setBackground(new java.awt.Color(15, 20, 40));
        tablaSocios.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
    {
        setBackground(new java.awt.Color(0, 150, 120));
        setForeground(java.awt.Color.WHITE);
        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }
});
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Consultar Socios");
        Logica.HerramientasVisuales.ponerIconoJavaFit(this);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaAdmin != null) {
                    ventanaAdmin.setVisible(true);
                }
            }
        });
        cargarSocios();
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = tablaSocios.getSelectedRow();
            System.out.println("DEBUG - Fila seleccionada: " + fila);
            System.out.println("DEBUG - listaSociosActual: " + (listaSociosActual != null ? listaSociosActual.size() : "null"));
            if (fila != -1 && listaSociosActual != null) {
                actualizarPanelDetalles(listaSociosActual.get(fila));
        }
    }
});
        
    }
    /**
     * Obtiene la lista de socios del Gestor y la muestra en la tabla.
     * Vacía la tabla antes de rellenarla para evitar duplicados.
     */
    
    private void cargarSocios() {
        cargarSocios(Gestor.getSocios());
    }
    private void cargarSocios(ArrayList<Socio> listaAMostrar) {
        DefaultTableModel modelo = (DefaultTableModel) tablaSocios.getModel();
        modelo.setRowCount(0);

        this.listaSociosActual = listaAMostrar;
        for (Socio s : listaSociosActual) {
            modelo.addRow(new Object[]{
                s.getNombre(),
                s.getCorreo(),
                s.getTelefono(),
                s.getDireccion(),
                s.getTarjeta(),
                s.esVip() ? "Sí" : "No"
            });
        }
    }
    /**
     * Muestra los datos completos del socio seleccionado en el panel lateral.
     * @param s Socio seleccionado en la tabla.
     */
        private void actualizarPanelDetalles(Socio s) {
            String texto = "Nombre: " + s.getNombre() + "\n"
            + "Correo: " + s.getCorreo() + "\n"
            + "Teléfono: " + s.getTelefono() + "\n"
            + "Dirección: " + s.getDireccion() + "\n"
            + "Tarjeta: " + s.getTarjeta() + "\n"
            + "VIP: " + (s.esVip() ? "Sí" : "No");
            jEditorPane1.setText(texto);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        checkVip = new javax.swing.JCheckBox();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEditorPane1.setBackground(new java.awt.Color(30, 40, 65));
        jEditorPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jEditorPane1);

        jButton1.setText("Volver atrás");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tablaSocios.setBackground(new java.awt.Color(30, 40, 65));
        tablaSocios.setForeground(new java.awt.Color(255, 255, 255));
        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Teléfono", "Dirección", "Tarjeta de crédito", "¿VIP?"
            }
        ));
        jScrollPane1.setViewportView(tablaSocios);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo:");

        checkVip.setForeground(new java.awt.Color(255, 255, 255));
        checkVip.setText("Solo socios VIP");
        checkVip.addActionListener(this::checkVipActionPerformed);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonBuscar)
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkVip)
                            .addComponent(botonBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra la ventana y restaura el menú del administrador.
     * @param evt Evento de acción del botón.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if (ventanaAdmin!=null) {
            ventanaAdmin.setVisible(true);         
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVipActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String nombre = txtNombre.getText().trim();
        String correo = txtCorreo.getText().trim();
        boolean soloVip = checkVip.isSelected();
        
        // Llamamos a la lógica del Gestor
        ArrayList<Logica.Socio> resultados = Logica.Gestor.filtrarSocios(nombre, correo, soloVip);
        // Cargamos los datos en la tabla
        cargarSocios(resultados);
        
        if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se han encontrado socios con esos criterios.");
    }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JCheckBox checkVip;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
