package Interfaz;

import java.awt.Color;


/**
 *
 * @author gdsergio1307
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());
    private javax.swing.JFrame ventanaPrincipal;
    /**
     * Creates new form VentanaLogin
     * @param principal
     */
public VentanaLogin(javax.swing.JFrame principal) {
        this.ventanaPrincipal = principal;
        initComponents();
        
        this.getContentPane().setBackground(java.awt.Color.LIGHT_GRAY);
        
        this.setSize(710,415);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        // Configuramos para que al darle a la 'X' o al botón Volver pase esto:
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaPrincipal != null) {
                    ventanaPrincipal.setVisible(true);
                }
            }
        });
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iniciaContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        botonConfirmarInicio = new javax.swing.JButton();
        botonVolverLogin = new javax.swing.JButton();
        iniciaCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - Ventana de Inicio de Sesión");
        setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Correo electrónico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, 20));

        iniciaContraseña.setText("jPasswordField1");
        iniciaContraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iniciaContraseña.setFocusTraversalPolicyProvider(true);
        iniciaContraseña.addActionListener(this::iniciaContraseñaActionPerformed);
        getContentPane().add(iniciaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 210, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        botonConfirmarInicio.setLabel("Iniciar Sesión");
        botonConfirmarInicio.addActionListener(this::botonConfirmarInicioActionPerformed);
        getContentPane().add(botonConfirmarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        botonVolverLogin.setLabel("Volver atrás");
        botonVolverLogin.addActionListener(this::botonVolverLoginActionPerformed);
        getContentPane().add(botonVolverLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(iniciaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void iniciaContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciaContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciaContraseñaActionPerformed

    private void botonVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverLoginActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverLoginActionPerformed

    private void botonConfirmarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarInicioActionPerformed

        // Usamos trim() para quitar espacios accidentales
        String emailIntroducido = iniciaCorreo.getText().trim();
        String pass = new String(iniciaContraseña.getPassword()).trim();

        System.out.println("DEBUG: Intentando entrar con [" + emailIntroducido + "]");

        boolean accesoConcedido = false;
        Logica.Socio socioActual = null;

        // IMPORTANTE: Asegúrate de que Gestor.getSocios() no esté vacío
        for (Logica.Socio s : Logica.Gestor.getSocios()) {
            // Usamos equalsIgnoreCase y trim para máxima compatibilidad
            if (s.getCorreo().trim().equalsIgnoreCase(emailIntroducido) &&
                s.getContraseña().trim().equals(pass)) {

                accesoConcedido = true;
                socioActual = s;
                break;
            }
        }

        if (accesoConcedido && socioActual != null) {
    // 1. Quitamos los listeners para que al cerrar esta no se abra la anterior
    for (java.awt.event.WindowListener wl : this.getWindowListeners()) {
        this.removeWindowListener(wl);
    }

    // 2. Crear y mostrar el menú del socio
    VentanaMenuSocio menuSocio = new VentanaMenuSocio(socioActual);
    menuSocio.setVisible(true);
    
    // 3. Si la ventana principal existe, la destruimos para que no quede en la barra de tareas
    if (ventanaPrincipal != null) {
        ventanaPrincipal.dispose();
    }
    
    // 4. Cerramos el Login
    this.dispose(); 
    } else {
    // Solo si falla mostramos el error
    javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
}

    }//GEN-LAST:event_botonConfirmarInicioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmarInicio;
    private javax.swing.JButton botonVolverLogin;
    private javax.swing.JPasswordField iniciaContraseña;
    private javax.swing.JTextField iniciaCorreo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
