/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Gestor;
import Logica.Socio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
/**
 *
 * @author gdsergio1307
 */
public class VentanaConsultarReservas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConsultarReservas.class.getName());
    private javax.swing.JFrame ventanaAdmin;
    private java.util.ArrayList<Logica.Reserva> listaReservasActual;
    private Logica.Administrador adminActual;
    /**
     * Creates new form VentanaConsultarReservas
     */
    public VentanaConsultarReservas(javax.swing.JFrame ventanaAdmin, Logica.Administrador admin) {
        this.ventanaAdmin = ventanaAdmin;
        this.adminActual = admin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Consultar Reservas");
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (ventanaAdmin != null) {
                ventanaAdmin.setVisible(true);
                ((VentanaConsultarReservas) ventanaAdmin).cargarReservas();
            }
        }
    });
        jEditorPane1.setEditable(false);
        Logica.Gestor.cargarReservas();
        cargarReservas();

        tablaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = tablaReservas.getSelectedRow();
            if (fila != -1 && listaReservasActual != null) {
                actualizarPanelDetalles(listaReservasActual.get(fila));
            }
        }
    });
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cargarReservas() {
        cargarReservas(Logica.Gestor.getReservas());
    }
    
    public void cargarReservas(ArrayList<Logica.Reserva> reservasAMostrar) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaReservas.getModel();
        modelo.setRowCount(0);
        
        this.listaReservasActual = reservasAMostrar;
        
        if (reservasAMostrar == null || reservasAMostrar.isEmpty()) {
            return;
        }
        
        for (Logica.Reserva reserva : listaReservasActual) {
        // Calculamos aforo restante

            boolean esEspecial = reserva.getActividad() instanceof Logica.Actividad_Especial;
            String precio = esEspecial ? ((Logica.Reserva) reserva).getPrecio_total() + "€" : "Incluido";
            String horario = reserva.getActividad().getHorario().getDia() + " " + reserva.getActividad().getHorario().getHora_inicio() + "-" + reserva.getActividad().getHorario().getHora_final();

            modelo.addRow(new Object[]{
                reserva.getSocio().getNombre(),
                reserva.getActividad().getTitulo(),
                reserva.getActividad().getHorario().getHora_inicio(),
                reserva.getPrecio_total(),
                reserva.getActividad().getTipo_Actividad().toString(),
                reserva.getActividad().getSala().getNombre(),
                reserva.getActividad().getMonitor_asignado(),horario,
                esEspecial ? "Sí" : "No",
                precio
            });
        }
    }
    private void actualizarPanelDetalles(Logica.Reserva reserva) {

        boolean esEspecial = reserva.getActividad() instanceof Logica.Actividad_Especial;
        String precio = esEspecial ? ((Logica.Reserva) reserva).getPrecio_total() + "€" : "Incluido";

        String texto = "Título: " + reserva.getActividad().getTitulo() + "\n"
            + "Tipo: " + reserva.getActividad().getTipo_Actividad().toString() + "\n"
            + "Sala: " + reserva.getActividad().getSala().getNombre() + "\n"
            + "Monitor: " + reserva.getActividad().getMonitor_asignado() + "\n"
            + "Día: " + reserva.getActividad().getHorario().getDia() + "\n"
            + "Horario: " + reserva.getActividad().getHorario().getHora_inicio() + " - " + reserva.getActividad().getHorario().getHora_final() + "\n"
            + "¿Especial?: " + (esEspecial ? "Sí" : "No") + "\n"
            + "Precio: " + precio;

        jEditorPane1.setText(texto);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        nombreActividad = new javax.swing.JTextField();
        botonTipoActividad = new javax.swing.JComboBox<>();
        boton_Dia = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Socio", "Nombre actividad", "Fecha", "Precio", "Tipo", "Sala", "Monitor"
            }
        ));
        jScrollPane1.setViewportView(tablaReservas);

        jButton1.setText("Volver atrás");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jScrollPane2.setViewportView(jEditorPane1);

        nombreActividad.setText("Nombre");
        nombreActividad.addActionListener(this::nombreActividadActionPerformed);

        botonTipoActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Yoga", "Musculacion", "Natacion", "Cardio" }));

        boton_Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        boton_Dia.addActionListener(this::boton_DiaActionPerformed);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        jLabel1.setText("Tipo Actividad");

        jLabel2.setText("Dia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(nombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonBuscar)
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(nombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonBuscar))
                                .addGap(7, 7, 7)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if (ventanaAdmin!=null) {
            ventanaAdmin.setVisible(true);         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActividadActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Recoger los datos de la interfaz
        String nombreTemporal = nombreActividad.getText().trim().toLowerCase();
        
        // 2. Lo modificamos si hace falta
        if (nombreTemporal.equals("nombre")) {
            nombreTemporal = "";
        }
        final String nombre = nombreTemporal;
        String tipo = botonTipoActividad.getSelectedItem().toString();
        String dia = boton_Dia.getSelectedItem().toString();
        
        ArrayList<Logica.Reserva> reservasFiltradas = Logica.Gestor.getReservas().stream()
                .filter(r -> nombre.isEmpty() || r.getActividad().getTitulo().toLowerCase().contains(nombre))
                .filter(r -> tipo.equals("Cualquiera") || r.getActividad().getTipo_Actividad().toString().equals(tipo))
                .filter(r -> dia.equals("Cualquiera") || r.getActividad().getHorario().getDia().equals(dia))
        
        .collect(Collectors.toCollection(ArrayList:: new));
        
        cargarReservas(reservasFiltradas);
        
        if (reservasFiltradas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se han encontrado reservas con estos criterios");
        }
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void boton_DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_DiaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JComboBox<String> botonTipoActividad;
    private javax.swing.JComboBox<String> boton_Dia;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreActividad;
    private javax.swing.JTable tablaReservas;
    // End of variables declaration//GEN-END:variables
}
