package Interfaz;

import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Socio;
import Logica.Gestor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Ventana que muestra los resultados de la búsqueda de actividades deportivas en JavaFit.
 * Presenta una tabla con las actividades filtradas y un panel lateral con la imagen y descripción de la actividad seleccionada. Permite al socio reservar una actividad.
 * Los socios VIP obtienen un 10% de descuento en actividades especiales.
 */
public class VentanaResultadosActividades extends javax.swing.JFrame {
    
    /** Socio que está consultando y puede reservar actividades. */
    private Socio socioLogueado;
    /** Lista de actividades mostradas en la tabla, sincronizada con las filas. */
    private ArrayList<Actividad_Deportiva> listaActividadesActual;
    
    /** Referencia al menú del socio para restaurarlo al volver. */
    private javax.swing.JFrame ventanaAnterior;


    private javax.swing.JFrame ventanaMenu;
    
    /**
     * Constructor de VentanaResultadosActividades.
     * Configura la ventana y añade el listener de clic sobre la tabla.
     * @param menu Ventana del menú del socio desde la que se navega.
     * @param socio Socio que está realizando la búsqueda.
     */
    public VentanaResultadosActividades(javax.swing.JFrame menu, Socio socio) {
        initComponents();
        this.ventanaMenu = menu;
        this.socioLogueado = socio; // Guardamos el socio que nos pasan
        this.setSize(900, 500);
        this.setLocationRelativeTo(null); // Centra la ventana
        this.setResizable(false);        // Bloquea el tamaño
        this.setTitle("JAVAFIT - Resultados de Búsqueda");
        
        // AÑADIMOS EL EVENTO DE CLIC A LA TABLA
        TablaResultados.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = TablaResultados.getSelectedRow();
            if (fila != -1 && listaActividadesActual != null) {
                // Obtenemos la actividad de la lista usando el índice de la fila
                Actividad_Deportiva seleccionada = listaActividadesActual.get(fila);
                actualizarPanelDetalles(seleccionada);
            }
        }
    });
    }
    
    /**
     * Actualiza el panel lateral con la descripción e imagen de la actividad seleccionada.
     * Si es una actividad especial muestra su descripción propia; si no, muestra los datos generales de la actividad.
     * @param act Actividad seleccionada en la tabla.
     */
    private void actualizarPanelDetalles(Actividad_Deportiva act) {
    // 1. Descripción
        if (act instanceof Actividad_Especial) {
            Actividad_Especial especial = (Actividad_Especial) act;
            txtDescripcion.setText(especial.getDescripcion());
        } else {
            String texto = "Actividad: " + act.getTitulo() + "\n"
                + "Monitor: " + act.getMonitor_asignado() + "\n"
                + "Sala: " + act.getSala().getNombre() + "\n"
                + "Aforo: " + act.getSala().getAforo_maximo() + " personas.";
                txtDescripcion.setText(texto);
        }

    // 2. Imagen
    ImageIcon icono = act.getImagen();
    if (icono != null && icono.getImage() != null) {
        // Usamos tamaño fijo en lugar de getWidth()/getHeight()
        int ancho = 280;
        int alto = 130;

        java.awt.Image imgEscalada = icono.getImage()
                .getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);

        lblFoto2.setIcon(new ImageIcon(imgEscalada));
        lblFoto2.setText("");
    } else {
        lblFoto2.setIcon(null);
        lblFoto2.setText("Sin imagen");
    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        botonVolver = new javax.swing.JButton();
        botonReservarActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JEditorPane();
        lblFoto2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        botonVolver.setText("Volver atrás");
        botonVolver.addActionListener(this::botonVolverActionPerformed);

        botonReservarActividad.setText("Reservar Actividad");
        botonReservarActividad.addActionListener(this::botonReservarActividadActionPerformed);

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Actividad", "Tipo", "Sala (Aforo)", "Día", "Horario ", "Monitor", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        jScrollPane2.setViewportView(txtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(botonReservarActividad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFoto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonVolver)
                            .addComponent(botonReservarActividad)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra la ventana de resultados y restaura el menú del socio.
     * @param evt Evento de acción del botón.
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        if (ventanaMenu != null) {
            ventanaMenu.setVisible(true);
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Reserva la actividad seleccionada en la tabla para el socio logueado.
     * Muestra un mensaje según el resultado: éxito, duplicado o aforo completo.
     * @param evt Evento de acción del botón.
     */
    private void botonReservarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActividadActionPerformed
        int fila = TablaResultados.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una actividad de la tabla.");
            return;
        }

        Actividad_Deportiva seleccionada = listaActividadesActual.get(fila);
        
        // Llamada al método de reserva que añadimos al Gestor
        String resultado = Gestor.realizarReserva(socioLogueado, seleccionada);

        switch (resultado) {
            case "EXITO":
                JOptionPane.showMessageDialog(this, "¡Reserva confirmada!");
                break;
            case "DUPLICADO":
                JOptionPane.showMessageDialog(this, "Ya tienes una reserva para esta actividad.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case "LLENO":
                JOptionPane.showMessageDialog(this, "Lo sentimos, no quedan plazas libres.", "Aforo completo", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }//GEN-LAST:event_botonReservarActividadActionPerformed

    /**
     * Recibe la lista de actividades filtradas y las muestra en la tabla.
     * Aplica descuento del 10% en el precio para socios VIP en actividades especiales.
     * @param lista Lista de actividades a mostrar en la tabla.
     */
    public void cargarDatosEnTabla(ArrayList<Actividad_Deportiva> lista) {
        this.listaActividadesActual = lista;
        DefaultTableModel modelo = (DefaultTableModel) TablaResultados.getModel();
        modelo.setRowCount(0); 
        
        for (Actividad_Deportiva act : lista) {
            String salaInfo = act.getSala().getNombre() + " (" + act.getSala().getAforo_maximo() + ")";
            String horarioInfo = act.getHorario().getHora_inicio() + " - " + act.getHorario().getHora_final();
            String precioStr = "Incluido";
            
            if (act instanceof Actividad_Especial){
                Actividad_Especial especial = (Actividad_Especial) act;
                double precio = especial.getPrecio();
                
                if (socioLogueado != null && socioLogueado.esVip()) {
                    double precioRebajado = precio * 0.90;
                    precioStr = String.format("%.2f€ (VIP)", precioRebajado);
                } else {
                    precioStr = precio + "€";
                }
            }

            Object[] fila = {
                act.getTitulo(),
                act.getTipo_Actividad().toString(),
                salaInfo,
                act.getHorario().getDia(),
                horarioInfo,
                act.getMonitor_asignado(),
                precioStr
            };
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaResultados;
    private javax.swing.JButton botonReservarActividad;
    private javax.swing.JButton botonVolver;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JEditorPane txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
