package Interfaz;

import Logica.Socio;
import Logica.Actividad_Deportiva;
import java.util.ArrayList;

/**
 *
 * @author gdsergio1307
 */
public class VentanaBuscarActividad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBuscarActividad.class.getName());

    /**
     * Creates new form VentanaReservarActividad
     */
    private javax.swing.JFrame ventanaMenu;
    private Socio socioActual;

    public VentanaBuscarActividad(javax.swing.JFrame menu, Socio socio) {
        this.ventanaMenu = menu;
        this.socioActual = socio;
        initComponents();
        
        
        this.setSize(710, 415);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaMenu != null) {
                    ventanaMenu.setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscar = new javax.swing.JButton();
        buscaTipoActividad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        buscarDiaSemana = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        buscarMonitor = new javax.swing.JComboBox<>();
        botonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        buscaTipoActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Yoga", "Musculación", "Natación", "Cardio" }));
        buscaTipoActividad.addActionListener(this::buscaTipoActividadActionPerformed);

        jLabel1.setText("Tipo de Actividad");

        buscarDiaSemana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sábado", "Domingo" }));

        jLabel2.setText("Día de la semana");

        buscarMonitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Monitor 1", "Monitor 2", "Monitor 3", "Monitor 4" }));
        buscarMonitor.addActionListener(this::buscarMonitorActionPerformed);

        botonVolver.setText("Volver atrás");
        botonVolver.addActionListener(this::botonVolverActionPerformed);

        jLabel3.setText("Monitor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarDiaSemana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(313, 313, 313)
                            .addComponent(buscarMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(botonVolver)))
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscaTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(botonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaTipoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTipoActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaTipoActividadActionPerformed

    private void buscarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMonitorActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose(); // Cierra esta ventana
        if (ventanaMenu != null) {
            ventanaMenu.setVisible(true); // Muestra el menú anterior
        }
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
                                             
    // 1. Obtener filtros
    String tipo = buscaTipoActividad.getSelectedItem().toString();
    String dia = buscarDiaSemana.getSelectedItem().toString();
    String monitor = buscarMonitor.getSelectedItem().toString();

    // 2. Obtener lista filtrada del Gestor
    java.util.ArrayList<Logica.Actividad_Deportiva> resultados = Logica.Gestor.filtrarActividades(tipo, dia, monitor);

    // 3. Crear la ventana de resultados
    VentanaResultadosActividades vResultados = new VentanaResultadosActividades(socioActual);
    
    // Centramos la ventana en la pantalla
    vResultados.setLocationRelativeTo(null);
    
    // Hacer que no se pueda maximizar ni cambiar el tamaño manualmente
    vResultados.setResizable(false);
    
    // 4. ¡IMPORTANTE! Llamar al método que acabas de arreglar para pasarle los datos
    vResultados.cargarDatosEnTabla(resultados);
    
    // 5. Mostrar la ventana
    vResultados.setVisible(true);
    
    // Hacer que desaparezca la ventana de búsqueda
    this.setVisible(false); // Cerramos la de búsqueda       
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> buscaTipoActividad;
    private javax.swing.JComboBox<String> buscarDiaSemana;
    private javax.swing.JComboBox<String> buscarMonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}