/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Gestor;
import Logica.Socio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gdsergio1307
 */
public class VentanaConsultarSocios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConsultarSocios.class.getName());
    private javax.swing.JFrame ventanaAdmin;
    private ArrayList<Socio> listaSociosActual;
    private Logica.Administrador adminActual;
    /**
     * Creates new form VentanaConsultarSocios
     */
    public VentanaConsultarSocios(javax.swing.JFrame ventanaAdmin, Logica.Administrador admin) {
        this.adminActual = admin;
        this.ventanaAdmin = ventanaAdmin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Consultar Socios");
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaAdmin != null) {
                    ventanaAdmin.setVisible(true);
                }
            }
        });
        cargarSocios();
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = tablaSocios.getSelectedRow();
            System.out.println("DEBUG - Fila seleccionada: " + fila);
            System.out.println("DEBUG - listaSociosActual: " + (listaSociosActual != null ? listaSociosActual.size() : "null"));
            if (fila != -1 && listaSociosActual != null) {
                actualizarPanelDetalles(listaSociosActual.get(fila));
        }
    }
});
        
    }
        private void cargarSocios() {
        DefaultTableModel modelo = (DefaultTableModel) tablaSocios.getModel();
        modelo.setRowCount(0);

        listaSociosActual = Gestor.getSocios();
        for (Socio s : listaSociosActual) {
            modelo.addRow(new Object[]{
                s.getNombre(),
                s.getCorreo(),
                s.getTelefono(),
                s.getDireccion(),
                s.getTarjeta(),
                s.esVip() ? "Sí" : "No"
            });
        }
    }
        private void actualizarPanelDetalles(Socio s) {
            String texto = "Nombre: " + s.getNombre() + "\n"
            + "Correo: " + s.getCorreo() + "\n"
            + "Teléfono: " + s.getTelefono() + "\n"
            + "Dirección: " + s.getDireccion() + "\n"
            + "Tarjeta: " + s.getTarjeta() + "\n"
            + "VIP: " + (s.esVip() ? "Sí" : "No");
            jEditorPane1.setText(texto);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Teléfono", "Dirección", "Tarjeta de crédito", "¿VIP?"
            }
        ));
        jScrollPane1.setViewportView(tablaSocios);

        jScrollPane3.setViewportView(jEditorPane1);

        jButton1.setText("Volver atrás");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if (ventanaAdmin!=null) {
            ventanaAdmin.setVisible(true);         
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaSocios;
    // End of variables declaration//GEN-END:variables
}
