/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Actividad_Deportiva;
import Logica.Actividad_Especial;
import Logica.Gestor;
import Logica.Socio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gdsergio1307
 */
public class VentanaConsultarReservas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConsultarReservas.class.getName());
    private javax.swing.JFrame ventanaAdmin;
    private java.util.ArrayList<Logica.Reserva> listaReservasActual;
    private Logica.Administrador adminActual;
    /**
     * Creates new form VentanaConsultarReservas
     */
    public VentanaConsultarReservas(javax.swing.JFrame ventanaAdmin, Logica.Administrador admin) {
        this.ventanaAdmin = ventanaAdmin;
        this.adminActual = admin;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("JAVAFIT - Consultar Reservas");
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (ventanaAdmin != null) {
                ventanaAdmin.setVisible(true);
                ((VentanaConsultarReservas) ventanaAdmin).cargarReservas();
            }
        }
    });
        jEditorPane1.setEditable(false);
        Logica.Gestor.cargarReservas();
        cargarReservas();

        tablaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int fila = tablaReservas.getSelectedRow();
            if (fila != -1 && listaReservasActual != null) {
                actualizarPanelDetalles(listaReservasActual.get(fila));
            }
        }
    });
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cargarReservas() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaReservas.getModel();
        modelo.setRowCount(0);

        listaReservasActual = Logica.Gestor.getReservas();
        
        if (listaReservasActual == null || listaReservasActual.isEmpty()) {
            return;
        }
        for (Logica.Reserva reserva : listaReservasActual) {
        // Calculamos aforo restante

            boolean esEspecial = reserva.getActividad() instanceof Logica.Actividad_Especial;
            String precio = esEspecial ? ((Logica.Reserva) reserva).getPrecio_total() + "€" : "Incluido";
            String horario = reserva.getActividad().getHorario().getDia() + " " + reserva.getActividad().getHorario().getHora_inicio() + "-" + reserva.getActividad().getHorario().getHora_final();

            modelo.addRow(new Object[]{
                reserva.getSocio().getNombre(),
                reserva.getActividad().getTitulo(),
                reserva.getActividad().getHorario().getHora_inicio(),
                reserva.getPrecio_total(),
                reserva.getActividad().getTipo_Actividad().toString(),
                reserva.getActividad().getSala().getNombre(),
                reserva.getActividad().getMonitor_asignado(),horario,
                esEspecial ? "Sí" : "No",
                precio});
    }
}
    private void actualizarPanelDetalles(Logica.Reserva reserva) {

        boolean esEspecial = reserva.getActividad() instanceof Logica.Actividad_Especial;
        String precio = esEspecial ? ((Logica.Reserva) reserva).getPrecio_total() + "€" : "Incluido";

        String texto = "Título: " + reserva.getActividad().getTitulo() + "\n"
            + "Tipo: " + reserva.getActividad().getTipo_Actividad().toString() + "\n"
            + "Sala: " + reserva.getActividad().getSala().getNombre() + "\n"
            + "Monitor: " + reserva.getActividad().getMonitor_asignado() + "\n"
            + "Día: " + reserva.getActividad().getHorario().getDia() + "\n"
            + "Horario: " + reserva.getActividad().getHorario().getHora_inicio() + " - " + reserva.getActividad().getHorario().getHora_final() + "\n"
            + "¿Especial?: " + (esEspecial ? "Sí" : "No") + "\n"
            + "Precio: " + precio;

        jEditorPane1.setText(texto);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Socio", "Nombre actividad", "Fecha", "Precio", "Tipo", "Sala", "Monitor"
            }
        ));
        jScrollPane1.setViewportView(tablaReservas);

        jButton1.setText("Volver atrás");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        if (ventanaAdmin!=null) {
            ventanaAdmin.setVisible(true);         
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaReservas;
    // End of variables declaration//GEN-END:variables
}
