package Interfaz;
/**
 * Ventana del menú principal del administrador en JavaFit.
 * Permite al administrador acceder a la gestión de actividades,
 * consulta de socios, consulta de reservas y cerrar sesión.
 * @author gdsergio1307
 */
public class VentanaMenuAdmin extends javax.swing.JFrame {
    
    /** Administrador que ha iniciado sesión. */
    private Logica.Administrador adminActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuAdmin.class.getName());

    /**
     * Constructor de VentanaMenuAdmin.
     * @param admin Administrador que ha iniciado sesión correctamente.
     */
    public VentanaMenuAdmin(Logica.Administrador admin) {
        this.adminActual = admin;
        initComponents();
        
        this.setSize(710, 415);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        botonGestionarActividades = new javax.swing.JButton();
        botonConsultaSocios = new javax.swing.JButton();
        botonConsultaReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        botonGestionarActividades.setText("Gestionar Actividades");
        botonGestionarActividades.addActionListener(this::botonGestionarActividadesActionPerformed);

        botonConsultaSocios.setText("Consulta de socios");
        botonConsultaSocios.addActionListener(this::botonConsultaSociosActionPerformed);

        botonConsultaReservas.setText("Consulta de Reservas");
        botonConsultaReservas.addActionListener(this::botonConsultaReservasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonConsultaReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonGestionarActividades, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addComponent(botonConsultaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(botonConsultaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra la sesión del administrador y vuelve a la ventana principal.
     * @param evt Evento de acción del botón.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); // Cerramos el menú actual
        //Creamos y mostramos la ventana principal de inicio
        VentanaPrincipal inicio = new VentanaPrincipal();
        inicio.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Abre la ventana de gestión de actividades donde el admin puede consultar, crear y eliminar actividades.
     * @param evt Evento de acción del botón.
     */
    private void botonGestionarActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarActividadesActionPerformed
        if (this.adminActual != null) {
            VentanaConsultarActividad vca = new VentanaConsultarActividad(this, this.adminActual);
            vca.setVisible(true);
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay un admin logueado.");
        }
    }//GEN-LAST:event_botonGestionarActividadesActionPerformed

    /**
     * Abre la ventana de consulta de socios donde el admin puede ver los datos de todos los socios registrados.
     * @param evt Evento de acción del botón.
     */
    private void botonConsultaSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaSociosActionPerformed
        if (this.adminActual != null) {
            VentanaConsultarSocios vcs = new VentanaConsultarSocios(this, this.adminActual);
            vcs.setVisible(true);
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay un admin logueado.");
        }
    }//GEN-LAST:event_botonConsultaSociosActionPerformed

    /**
     * Abre la ventana de consulta de reservas donde el admin puede ver todas las reservas activas del sistema.
     * @param evt Evento de acción del botón.
     */
    private void botonConsultaReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaReservasActionPerformed
        if (this.adminActual != null) {
            VentanaConsultarReservas vcr = new VentanaConsultarReservas(this, this.adminActual);
            vcr.setVisible(true);
            this.setVisible(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No hay un admin logueado.");
        } 
    }//GEN-LAST:event_botonConsultaReservasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultaReservas;
    private javax.swing.JButton botonConsultaSocios;
    private javax.swing.JButton botonGestionarActividades;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
