/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
/**
 *
 * @author gdsergio1307
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        Logica.Gestor.cargarSocios();
        // 1. Creamos el panel con la ruta de tu imagen en resources
         PanelFondo contenedorFondo = new PanelFondo("/imagenes/imagen_inicio.jpg");

    
        // 2. Le ponemos el mismo layout para que el Design funcione bien
        contenedorFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
        // 3. Sustituimos el panel por defecto por el nuestro [cite: 651, 652]
        this.setContentPane(contenedorFondo);
    
        // 4. Inicializamos los componentes (botones, etc.)
        initComponents();
        // Chivato para confirmar que funcionó
        System.out.println("Carga inicial finalizada. Socios en memoria: " + Logica.Gestor.getSocios().size());
    
        // 5. Centramos y damos tamaño
        this.setSize(710, 415);
        this.setLocationRelativeTo(null); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JButton();
        botonRegistrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaFit - Menú de Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("JavaFit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 20));

        botonIniciarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonIniciarSesion.setLabel("Iniciar Sesión");
        botonIniciarSesion.addActionListener(this::botonIniciarSesionActionPerformed);
        getContentPane().add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 190, 40));

        botonRegistrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonRegistrarse.setLabel("Registrarse");
        botonRegistrarse.addActionListener(this::botonRegistrarseActionPerformed);
        getContentPane().add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        VentanaLogin ventanaDatos = new VentanaLogin(this);
        this.setVisible(false);
        ventanaDatos.setVisible(true);
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        VentanaRegistro ventanaDatos = new VentanaRegistro(this);
        this.setVisible(false);
        ventanaDatos.setVisible(true);
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}

class PanelFondo extends javax.swing.JPanel {
    private java.awt.Image imagen;

    public PanelFondo(String rutaRecurso) {
        java.net.URL url = getClass().getResource(rutaRecurso);
        if (url != null) {
            this.imagen = new javax.swing.ImageIcon(url).getImage();
        }
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (imagen != null) {
            // Dibuja la imagen adaptada al tamaño total del panel [cite: 591]
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}